restraint-harness/restraint

docs/using.rst
The url provided in the documentation isn't valid anymore, let's use one
that is.
Signed-off-by: Jakub Racek <jracek@redhat.com>
=> docs: update reservesys task location

.packit.yaml
Packit is creating comments in Pull Request when the first build is finished successfully.
This is unnecessary noise. We should disable it in configuration [0].
[0] https://packit.dev/docs/configuration/#notifications
=> Disable Packit notification in pull request

.github/workflows/merge-checks.yml, .github/workflows/review-checks.yml, specfiles/restraint-upstream.spec
Recent changes made pidof a dependency for Restraint and checks running
on containers are failing because pidof is missing.
Add /usr/bin/pidof as requirement in upstream specfile.
Add procps-ng package to GitHub workflows dependency steps.
Note that requirement for downstream will be addressed separately.
Fixes #16
=> Add pidof as dependency for upstream

docs/using.rst
Small patch to address issues with documentation.
Update Fedora reference a bit + Explain more purpose of custom repo.
Initially, this PR should address #11 but I dropped it in favor of #14. We have to embrace our open source community.
=> Update Restraint documentation regarding execution with Beaker

src/run-tests.sh
When the Git daemon is not available, tests that depend on it are
skipped. Some tests were missing from the skip list.
Add git tests to the skip list.
Add the --keep-going option to avoid the test suite to fail when all
tests are skipped.
=> tests: Add git tests to skip without git daemon

containers/provision/fedora:latest.sh
The pidof program is required by restraint and it's needed in tests.
=> tests: Add procps-ng dep for containers

src/cmd_watchdog.c
The error used during parsing was being overwritten, as reported by
GLib:
GError set over the top of a previous GError or uninitialized memory.
This indicates a bug in someone's code.
You must ensure an error is NULL before it's set.
The overwriting error message was: Wrong arguments
=> Fix error handling on rstrnt-adjust-watchdog

src/errors.c, src/errors.h
As sugested in GLib's error reporting docs.
=> refactor: Use G_DEFINE_QUARK for errors

.gitignore, src/Makefile, src/test-dummies/cmd_utils/bin/pidof, src/test-dummies/cmd_utils/bin/spawned_mock, src/test_cmd_utils.c
Add unit tests for get_restraintd_pid.
Add basic mocking for spawned programs.
Relates to #34
=> tests: Add cmd_utils unit tests

src/test_cmd_utils.c
Cases covered:
- Variables not set
- Variables empty
- Variables set
- Variables set with prefix
=> tests: Cover get_taskid and get_recipe_url

docs/commands.rst, docs/install.rst, init.d/restraintd, init.d/restraintd.service, src/client.c, src/client.h, src/server.c
In release 0.2.0 the restraintd port is chosen randomly for each run. Before this release, restraintd used the port 8081 as default, and some workflows, like /distribution/reservesys in beaker-core-tasks, relied on having a static port.
Adding back the option to specify the restraintd port will allow to make the port static when needed, and keep it dynamic when it isn't.
+ Add `-p, --port` option to server and client. If the option is not used, a free port will be chosen randomly
+ Use port 8081 when running restraintd as a system service
+ Add reference to `-p, --port` option and system service port to docs
Closes #28
=> Allow to specify restraintd port

src/server.c
Buffer was used directly in g_message call, but there is no guarantee
that it's going to be null terminated.
Use logging as before removal of libssh.
Fixes #45
=> Revert logging in server_io_callback

src/server.c
When signals are received and processed, they are now being logged.
However, the g_error call also calls abort which is appearing
in user's log when they run abrt-cli list.  Replace it with
g_message resolves this issue.
Background:  The user was shutting down services which caused the TERMINATE trap
to  get logged which is how restraintd executed abort by way of g_error.
Bug: 1823840
=> Replace call to g_error when report signal

docs/commands.rst, docs/index.rst, docs/plugins.rst, docs/remove_rhts.rst, docs/tasks.rst, docs/variables.rst
Users should stop using RHTS extension or RHTS library and use
restraint only.  This changeset documents steps needed to
remove RHTS and lists substitutes for RHTS scripts, variables,
and metadata file.
Bug: 1802610
=> Doc: Detail how to remove rhts from jobs

docs/commands.rst, restraint.spec, specfiles/restraint-upstream.spec, src/cmd_abort.c, src/cmd_log.c, src/cmd_result.c, src/cmd_utils.c, src/cmd_utils.h, src/cmd_watchdog.c, src/env.c, src/env.h, src/server.c, src/server.h, src/task.c, src/test_cmd_abort.c, src/test_cmd_log.c, src/test_cmd_result.c, src/test_cmd_utils.c, src/test_cmd_watchdog.c, src/test_env.c, src/test_utils.c, src/utils.c, src/utils.h
There are some issues with including call to pidof and pgrep from
restraint commands.  To eliminate OS calls, we must eliminate the
new argument option -c|--current.  Also -i|--pid was associated with
this option and it is replaced with --port.
Issue #51, Issue #44
=> Fix: Revisit restraint commands

src/process.c, src/test_process.c
The removal of libssh library from Restraint introduced changes in the way that process utilizes stdin. Changes were made to allow Restraint client to pass the job.xml file to `restraintd` through `stdin`.
- `fd_in` is used uninitialized when pty is requested, and close is done on parent stdin FD. This is causing #26 
- stdin for child process is redirected to a pipe instead of `/dev/null`. This is causing #26, although the root cause remains unknown.
Both issues can be addressed redirecting child process stdin to pipe only when content input needs to be passed. This allows restraintd to keep reading from stdin, and keeps stdin behavior during task execution as when libssh was used.
Fixes #24, fixes #26
=> Revert process stdin behavior

src/process.c, src/server.c, src/task.c
Calls to g_error result in core dump and they are not intended to report expected errors.
Replace calls to g_error with g_warning and g_printerr. The later is preferred for reporting to the command line.
Closes #53
=> fix: Replace calls to g_error

docs/commands.rst, src/cmd_abort.c, src/cmd_log.c, src/cmd_result.c, src/cmd_utils.h, src/cmd_watchdog.c, src/test_utils.c
Pull # 52 was merged too early missing comments from peers.  This
changeset addresses those comments. The changes include:
* Update docs for --port option in restraint commands
* Remove references to --current in commands context summary
* Reference restraintd service default port in --port option description
* Improve test_environment_file
Fixes: #51, Fixes #44
=> Fix: Address comments on command pull 52

src/test-dummies/cmd_utils/bin/rpm, src/test_utils.c, src/utils.c
The `rpm` command prints to stdout the package not installed message. In get_package_version, stderr is favored over stdout, hiding this message if some not related message is printed to stderr too.
- Change error handling to favor stdout over stderr
- Add test covering the error message source for get_package_version
Closes #62
=> Favor stdout over stderr on get_package_version

rel-eng/lib/restrainttito.py, rel-eng/tito.props
With this feature, we are able to bump both spec files during release. Completely remove issues where Fedora spec is not updated to the latest state.
Fixes: #63
=> Custom tagger for Tito

src/run-tests.sh
Eliminate duplicate prepend assignment where each call to run_valgrind adds value 'gc_friendly' to same variable (G_DEBUG).
=> test: Move GLib envars out of valgrind function

src/cmd_utils.c, src/cmd_utils.h, src/test_cmd_utils.c, src/utils.h
Add rstrnt_getenv with the logic for checking HARNESS_PREFIX and replace
get_recipe_url and get_taskid with macros.
Test rstrnt_getenv covering:
- Variable not set
- Variable empty
- Variable set
- Variable set with prefix
=> refactor: get_recipe_url and get_taskid

src/task.c
These changes are inline with the recent ones in server_io_callback, #45, to revert logging behavior to the one in restraint-0.1.45.
- Fix incorrect use of buffer. g_debug is replaced with fwrite.
- Replace g_message with g_print
Relates to #12
=> Revert logging in task io callback

docs/develop.rst
Following things are addressed in docs:
- Gerrit is no longer used, instead of that we should point users to GitHub
- Favor `DNF` instead of `YUM`, most of contributors may run Fedora rather than EL system.
=> docs: update developer guide with latest info

docs/develop.rst, reno.yaml
At this point release notes are managed manually and some of has to manually go thru all issues and list it together and figure out what was the point of the fix. This is really inflexible if we take the time to make another release.
Instead of that, we can use the tool [Reno](https://docs.openstack.org/reno/latest/).
A person who is created patch will also create a small description of the patch.
To create boilerplate user should use
```bash
$ reno new slug-goes-here
```
Output:
```bash
Created new notes file in releasenotes/notes/slug-goes-here-95915aaedd3c48d8.yaml
```
or
```bash
$ tox -e venv -- reno new slug-goes-here
```
Output:
```
venv develop-inst-nodeps: /mnt/projects/release-notes-generation/reno
venv runtests: commands[0] | reno new slug-goes-here
Created new notes file in …
```
=> Introduce Reno for creating release notes

restraint.spec
BuildRequires for non static building were included checking the `without_static` macro, but this was not defined when the option `--without=static` was used.
Add BuildRequires for non static building by checking if the `with_static` macro is not defined.
Resolves #72
=> fix: BuildRequires for non static building

containers/provision/centos:8.sh, containers/provision/fedora:30.sh, containers/provision/fedora:latest.sh
- Add CentOS 8
- Remove Fedora 30
- Remove procps-ng package from Fedora provision scripts
=> Update container provision scripts

releasenotes/notes/fix-commands-exit-958e93a3c928ce80.yaml, src/client.c, src/cmd_abort_main.c, src/cmd_log_main.c, src/cmd_watchdog_main.c
Exit status for Restraint commands was misleading due to use of `error->code` as value. As 0 is an actual error code, the command failed successfully.
Replace `error->code` with `EXIT_FAILURE` for exit status in,
- Restraint client
- rstrnt-abort
- rstrnt-adjust-watchdog
- rstrnt-report-log
Resolves #79
=> fix: Restraint commands exit status

rel-eng/lib/restrainttito.py
Tito is getting smarter and trying to do new things.
In the last release, they introduce a technique to copy all sources from the given spec file. This is something that will break our workflow where 3rd party Makefile handles sources.
=> Fix error during tito srpm builds

src/task.c
The task member 'version' was never freed.
=> fix: task version leak

src/server.c
Instead of a boolean indicating if the server is listening or not, return the port where the server is listening, or 0 if it's not listening. With this change we can remove the code that was used to get the port after the call.
The list returned by `soup_server_get_uris` and the URIs in it should be freed by the caller. Use `g_slist_free_full` with `g_soup_uri_free` instead of `g_slist_free`.
=> Refactor rstrnt_listen_any_local

src/server.c
The GCancellable "cancellable" object in server data was never freed.
=> fix: GCancellable leak in server data

src/recipe.c
The string from "get_attribute" was never freed.
=> Fix leak in recipe_parse

src/server.c
- `data_table` was leaking the hash table from `soup_form_decode`
- A watchdog request without `seconds` in the form data crashed restraintd due to `g_ascii_strtoull` called with a NULL pointer.
=> Fix unsafe watchdog handling

src/client.c
Members of `recipe_data` were not freed in `restraint_free_recipe_data`,
+ cancellable is allocated in `new_recipe_data` but never freed
+ `rhost` and `connect_uri` are allocated during host parsing, but never freed
In `handle_message`, the json object returned by `json_tokener_parse` was never freed, and correcting it revealed that the destroy key function used in the hash table returned by `json_to_hashtable` was freeing the json object's own allocated key, leaving the object in a bad state.
=> Fix leaks in Restraint client

src/client.c
These changes were left out from #69 to speed up the reviews.
- Fix style in `parse_host` and `add_recipe_host`
- Check argument values in `add_recipe_host` and unify parse check and return value
- Increment `recipe_id` in the loop, instead of `add_recipe_host`
- Reduce indentation in loop for host parsing and use the NULL-terminated array for iteration
- Set default for connection retries option before parsing
=> Refactor host parsing in Restraint client

releasenotes/notes/client_recipe_params-44e597287474ee53.yaml, src/client.c
This PR fixes a bug in restraint client where it doesn't
honor recipe level params.
Change-Id: I6fd600327cdf951d00f0d66e6a1283eccbe8d223
=> Fix restraint client to support recipe params

.gitignore, tox.ini
```
mastyk@mcas: /home/mastyk/work/github.com/StykMartin/restraint git:(one-tox-please) ✗ 
➜   tox -e docs                          
docs installed: alabaster==0.7.12,Babel==2.8.0,certifi==2020.4.5.1,chardet==3.0.4,docutils==0.16,idna==2.9,imagesize==1.2.0,Jinja2==2.11.2,MarkupSafe==1.1.1,packaging==20.4,Pygments==2.6.1,pyparsing==2.4.7,pytz==2020.1,requests==2.23.0,six==1.15.0,snowballstemmer==2.0.0,Sphinx==1.8.5,sphinxcontrib-websupport==1.2.2,urllib3==1.25.9
docs run-test-pre: PYTHONHASHSEED='1619422057'
docs run-test: commands[0] | sphinx-build docs docs/_build/html --color -bhtml
Running Sphinx v1.8.5
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 …
```
=> Add tox support for docs creation

rel-eng/lib/restrainttito.py
Tito made change in method during 0.6.14 release.
Method is no longer private therefore we have to update method signature in same way.
Change in tito: 
https://github.com/rpm-software-management/tito/commit/c3c1de77ccb8a85ea79ae1eae51043105eb8fb57
=> fix: update copy_extra_sources method to match tito signature

releasenotes/notes/fix-noisy-client-output-7131109005ba0a1c.yaml, src/client.c, src/process.c, src/process.h, src/recipe.c, src/server.c, src/task.c, src/test_dependency.c, src/test_process.c
After the removal of libssh, communication between Restraint client and `restraintd` is done through stdout/stderr. In a nutshell, the stdout/stderr from `restraintd` is printed in the client. When `restraintd` is ran by the client, messages sent with `connections_write` are written to `restraintd` stdout too, so these shouldn't be printed outside `connections_write`, otherwise they will be duplicated without proper formatting to match them with the test host. In most cases this was controlled by printing these messages to stderr and suppressing stderr output with a null printer/writer.
- Fix client output format. Print to stdout and include the hostname where the recipe is running
- Add null print handler to suppress `g_printerr` output in `restraintd` when it runs through the client
- …
=> Fix noisy output in restraint client

releasenotes/notes/increase-fetch-retries-a02b493029ebd3ab.yaml, src/Makefile, src/recipe.c, src/recipe.h, src/server.h, src/task.c, src/task.h
As reported in #101, there are some corner cases where recipe fetching takes more than 30 seconds, somewhere close 60 seconds. Increasing the number of recipe fetching retries, so it keeps trying over 60 seconds, should cover this case.
- Refactor retry macro pairs, so values can be defined per operation, recipe fetching, tasks fetching and role refreshing
- Increase recipe fetching retries from 3 to 12. With a 10 seconds interval, from 30 to 120 seconds
Fixes #101
=> Increase retries for recipe fetching

docs/_static/theme_overrides.css, docs/conf.py, docs/remove_rhts.rst
There is a known bug where `readthedocs` doesn't allow table cells
to wrap.  As a result, the horizontal scroll bars are very long
making it difficult to view the table.  Details on this fix
was found from:
https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html
This anomaly is only with `readthedocs` and not seen with local
doc generation and viewing.
Fixes: #108
=> Allow text to wrap in tables

src/task.c, src/test_utils.c, src/utils.c, src/utils.h
In check_param_for_override, the whatchdog time is updated if the environment variables KILLTIMEOVERRIDE or STRNT_MAX_TIME are set. The value was used from parse_time_string without checking if the parsing succeeded.
- Add tests for parse_time_string
- Refactor parse_time_string
- Don't override task max_time if parse_time_string fails
=> fix: Don't override task max_time if time parsing fails

docs/commands.rst
The restraint command rstrnt-report-result has an undocumented
TESTRESULT called SKIP.  This documents this type as well as
details for its use.
Resolves: #116
=> FIX: Add SKIP result to rstrnt-report-result

specfiles/restraint-upstream.spec
=> Use parallel make %{?_smp_mflags} macro for Fedora builds

src/server.c
A request to adjust watchdog will take up to HEARTBEAT time to get the value updated. As time_chged is freed and set to NULL only after the value is updated, every request to adjust the watchdog sent before this will cause a leak:
```
==8587== 40 bytes in 5 blocks are definitely lost in loss record 1,629 of 2,470
==8587==    at 0x483A809: malloc (vg_replace_malloc.c:307)
==8587==    by 0x6219B8: g_malloc (gmem.c:99)
==8587==    by 0x636A81: g_memdup (gstrfuncs.c:391)
==8587==    by 0x40A3AE: server_recipe_callback (server.c:397)
==8587==    by 0x5C7DD9: g_closure_invoke (gclosure.c:804)
==8587==    by 0x5DA2F2: signal_emit_unlocked_R.isra.0 (gsignal.c:3635)
==8587==    by 0x5E094A: g_signal_emit_valist (gsignal.c:3391)
==8587==    by 0x5E0B92: g_signal_emit (gsignal.c:3447)
==8587==    by …
```
=> Fix time_chged leak in server_recipe_callback

.gitignore, containers/provision/centos:8.sh, containers/utils/build-rpms.sh
Can be used by running,
```
$ containers/run.sh ./containers/utils/build-rpms.sh
```
After build, packages will be available in the restraint/tito-test-build directory.
Works for CentOS 8, Fedora 31 and Fedora 32.
Fedora Rawhide works at the time of this PR.
=> containers: Add script to build rpms in containers

docs/commands.rst, docs/index.rst, docs/remove_rhts.rst, docs/results.rst, releasenotes/notes/SKIP-issue-nonrhts-task-7e414a198ce0cbb5.yaml, src/server.c, src/task.c, src/task.h
When the task reports just `SKIP` for results, the final task result
should be `SKIP`. When a non-rhts task is running, an extra task result
of `PASS` is occurring. Since `PASS` has a higher severity than `SKIP`,
`PASS` becomes the final task result. (note: a non-rhts task is one
defined using `metadata` file instead of `Makefile/testinfo` file.)
Bugzilla 1334893 made a change to always report results `PASS` or
`FAIL` for non-rhts tasks based on the process exit results without
considering results from user calls to `rstrnt-report-result`.
New Behavior when task process exits successfully:
Code changes monitor whether the user reports results by way of
`rstrnt-report-result`.  If so, give user `reported` results
priority; otherwise, provide a `PASS` task result for user.
Behavior when …
=> FIX: `SKIP` results fail for non-rhts tasks

legacy/bin/rhts-run-simple-test, plugins/task_run.d/20_unconfined
Use /bin/bash instead of /bin/sh as in some OSes /bin/sh is the Dash
shell and not the bash shell.
Also check if we have the selinuxenabled command before running it.
=> Make restraint less OS specific

.gitignore, docs/install.rst, restraint.spec, third-party/Makefile
Auto pointers and soup_message_headers_header_equals are nice to have.
=> third-party: Bump libsoup to 2.52.2

containers/utils/build-rpms.sh
By default, rpms are built with dynamic linking, saves time.
To build statically linked,
```
$ ./containers/run.sh ./containers/utils/build-rpms.sh static
```
=> containers: Add ability to build statically linked rpms

src/test_fetch_uri.c
An extension to fetch_uri test verifies that permissions are correct on file where we defined +x.
=> Extend test for fetch uri

docs/commands.rst, releasenotes/notes/no-chatty-LWD-log-3d0da15e99a968f4.yaml, src/client.c, src/task.c, src/task.h
When LWD (Local Watchdog) is disabled, there is a message in the
harness log that reports this every minute.  The message looks
like: `Localwatchdog at:  Disabled! `.  This changeset makes sure
it is no longer reported repeatedly when `no_localwatchdog=true`
is configured in the task `metadata` file.
To make sure the connection between client and server don't timeout,
the ssh arguments `ServerAliveInterval` and `ServerAliveCountMax` are
set on the `restraint` client. The `ServerAliveInterval` is set to
60 seconds while `ServerAliveCountMax` is set fo 5.  This results in
an idle timeout of 5 minutes.  The `ServerAliveCountMax` can be
altered by the user using `--timeout` argument.
Replaced localtime() with localtime_r() to resolve error reported
by the LGTM checker.
Bug: 1598329
=> Fix: Stop logging `LWD is disabled` every minute

.gitignore, releasenotes/notes/beaker-health-check-e9991e4fe5ee94ea.yaml, src/Makefile, src/beaker_harness.c, src/beaker_harness.h, src/recipe.c, src/recipe.h, src/task.c, src/test_beaker_harness.c
When Restraint runs under Beaker, check Beaker's health status and wait until it is good before performing,
- Recipe fetching
- Task role refreshing
- Task fetching
- Dependency install
The wait is done in the recipe handler, for recipe fetching, and the task handler for the other operations.
If health status is not good, restraint will wait 60 seconds before trying again.
The health status is taken from the recipe endpoint in the lab controller. This will give some guarantees that both, lab controller and Beaker server are in good condition.
This doesn't affect client/server operation.
Add Beaker harness lib with,
- Recipe endpoint health check
- Environment check
Closes #124
=> Wait on Beaker's health status

docs/remove_rhts.rst, legacy/Makefile, legacy/data/install_config, plugins/localwatchdog.d/20_sysinfo, releasenotes/notes/replace-mnt-directory-15ff8cb75c2b3210.yaml, restraint.spec, src/recipe.c, src/recipe.h, src/test_utils.c, src/utils.c, src/utils.h
FIX: Use new task install default for non-RHTS package
For restraint-rhts package, tasks are installed and executed
beneath `/mnt/tests`.  For non-rhts `restraint`
installations, this path has changed to a more appropriate
location.
The `20_sysinfo` plugin processes journalctl log in a temporary location
instead of `/mnt` as it is just an interim event.
closes: 74
closes:105
=> FIX: Add /var/lib/restraint/subdirs for non-RHTS

.gitignore, releasenotes/notes/log-manager-18fb90743f423087.yaml, src/Makefile, src/beaker_harness.h, src/logging.c, src/logging.h, src/server.c, src/server.h, src/task.c, src/task.h, src/test_logging.c
The log manager is used when restraintd runs under Beaker. Harness and taskout logs are cached by restraint until the task finishes. Logs are uploaded in chunks of 10MB, current maximum request size in the Beaker Lab Controller.
The log manager is not used when restraintd runs with the restraint client.
Closes #94
=> Log manager for log caching

.github/workflows/merge-checks.yml, .github/workflows/review-checks.yml
Explicitly define registry which we would like to use for container images.
In this case we should rely on Fedora source.
=> Use fedora-registry for Fedora container images

src/Makefile, src/task.c, src/test-data/bad.conf, src/test-data/task42.conf, src/test_task.c
Include task source in tests to be able to test private definitions.
Make `parse_task_config` private, as it's not used outside the task module and it was not declared in the header file.
Add test cases for parse_task_config:
- Config file doesn't exist
- Config file exists with values
- Config file exists with bad value
=> Add test cases for parse_task_config

src/task.c, src/task.h, src/test_task.c
The intent is to be able to use `restraint_task_get_offset` and `task_config_set_offset` in the log manager.
=> Refactor task config handling

src/task.c, src/test-data/bad.conf, src/test_task.c
- Add helper and tests to get offsets section from config file
- Cleanup error handling in parse_task_config
=> Refactor parse_task_config

containers/provision/fedora:33.sh
Now that Fedora 33 has branched, Add a container
provision script for it.
=> test: Add Fedora 33 container provision script

releasenotes/notes/incremental-log-manager-0e7bfc306f58570f.yaml, src/Makefile, src/logging.c, src/logging.h, src/server.c, src/server.h, src/task.c, src/test_logging.c
Previously, logs were uploaded only after the task completed. This behaviour introduced two issues,
- The task progress cannot be checked through Beaker
- The logs are not uploaded to Beaker if the recipe is cancelled by the user or aborted by the external watchdog
The purpose of the log manager is to reduce the amount of communication between Restraint and the Beaker Lab Controller, to reduce load on the Lab Controller itself and also on the network. Without the log manager, a "noisy" task can produce somewhere between 50 and 100 messages per second.
A solution to the issues introduced that allows to reduce the amount of communication with the Lab Controller is to keep caching the logs in the test machine and upload them progressively.
Incremental uploads on time intervals is implemented …
=> Upload logs incrementally on time intervals

src/logging.c
This is a temporary workaround before proper SELinux policies for `/var/lib/restraint` are defined.
=> fix: Move logs under /var/tmp

containers/provision/debian:latest.sh, debian/control, tests/run-tests.sh
Add some love for Debian through containers support for,
```
$ ./containers/run.sh -i debian:latest make clean all check valgrind
```
The script `debian/build-deb-package.sh` can be used,
```
$ ./containers/run.sh -i debian:latest ./debian/build-deb-package.sh`
```
Although needs some adjustments and clean up to get something similar as `containers/utils/build-rpms.sh`, perhaps `containers/utils/build-debs.sh`.
=> Debian containers

.gitignore, tests/Makefile
Add make targets to produce test coverage report using the gcov tool.
The check-coverage target compiles and runs the tests with the `--coverage` flag to produce the .gcno and .gcda data files, and runs gcov with the source files to produce the .gcov files.
=> test: Add coverage report

.gitignore, tests/Makefile, tests/httpserver.py, tests/test_upload.c
Add cases for,
- uploading a log file
- failure due to non existent file
The http server for tests now implements a dummy PUT method to handle requests from tests. It always returns 200 response.
=> Add test cases for upload_file

tests/test-data/config_types.conf, tests/test_config.c
For int64, uint64, boolean, string, covers,
- File not found
- Group not found
- Key not found
- Key with wrong value
- Key with proper value
For keys,
- File not found
- Group not found
- Group with keys
=> test: Add cases for config_get_ functions

src/config.c, tests/test_config.c
Refactoring in preparation for improving error handling.
- Dedupe `g_key_file_load_from_file ()` and `g_mkdir_with_parents ()` calls
- Remove bogus `disabled_root_access ()` error handling
- Remove unused `unrecognised()` macro
Relates to [bug: 1783283](https://bugzilla.redhat.com/show_bug.cgi?id=1783283).
=> Refactor config

plugins/task_run.d/20_unconfined, releasenotes/notes/fix-distro-check-in-20_unconfined-224494f732ed2cdd.yaml
First, on Rawhide fedora-release no longer provides redhat-release (I
mean why should it, really?), so try redhat-release first and then
fedora-release.
Second, the distro family wasn't actually being compared - fix that,
too.
And finally, add quotes where appropriate in this function and refactor
the flow a bit.
Closes: BKR-5033
=> Fix distro version check in 20_unconfined

releasenotes/notes/config-error-handling-2fce6360cfa35f3d.yaml, src/config.c, src/task.c, tests/test-data/ill_formed.conf, tests/test_config.c
Previously, the config functions didn't check errors on key file reading. In case of error, the key file structure was left either empty or partially loaded.
Other than the file not found error, which is tolerated on purpose, doesn't make much sense to ignore other errors, and the key file structure shouldn't be used at all after an error.
The case of partially loaded file could be the root cause in [bugzilla: 1783283](https://bugzilla.redhat.com/show_bug.cgi?id=1783283), although the state of the config file at that point is still unknown.
This is not going to fix a bad configuration file, but at least the error will get visibility.
- Add error handling for reading key files
- Make invalid type errors critical
- Print warning in connections write in case of errors in config_set
[Bug: …
=> Fix error handling in restraint config functions

releasenotes/notes/client-pass-job-id-468f019b18bad5ad.yaml, src/client.c
Restraint client ignores job_id attribute defined in <recipe> tag.
Restraintd is already capable to accept this attribute and we passing it with Beaker.
Behavior after PR.
```
[magic@box jobs]$ restraint -j re.xml -t root@master -vvv | grep -E "RSTRNT_JOBID=|RSTRNT_RECIPEID="
[192.168.42.9     ] + echo '- eval echo RSTRNT_RECIPEID=$RSTRNT_RECIPEID; echo RSTRNT_JOBID=$RSTRNT_JOBID'
[192.168.42.9      ] - eval echo RSTRNT_RECIPEID=$RSTRNT_RECIPEID; echo RSTRNT_JOBID=$RSTRNT_JOBID
[192.168.42.9      ] + eval echo 'RSTRNT_RECIPEID=$RSTRNT_RECIPEID;' echo 'RSTRNT_JOBID=$RSTRNT_JOBID'
[192.168.42.9      ] ++ echo RSTRNT_RECIPEID=1
[192.168.42.9      ] ++ echo RSTRNT_JOBID=42
[192.168.42.9      ] RSTRNT_RECIPEID=1
[192.168.42.9      ] RSTRNT_JOBID=42
```
Fixes: #188
=> Honor job_id defined in recipe tag.

.github/workflows/review-checks.yml
We are getting close to Fedora 34 release, therefore we should start validating the results on this distribution.
=> Run tests on Fedora 34

src/Makefile, tests/Makefile
This is not a big deal actually. The only case when we can encounter this is CI (for now).
The reason is that we using distro libraries for dependencies rather than third-party.
Production build is still using an obsolete version of Glib.
Revert this commit when the third-party is using Glib 2.68+ and the code is properly updated. 
=> Temporarily disable deprecation check

.github/workflows/review-checks.yml, rel-eng/lib/restrainttito.py
Introduce static builds.
This should mimic something close to our BREW builds (except RH, multiarch, etc...).
CentOS 8 is disabled at this moment as buildroot doesn't provide all required packages for compilation.
I would say the whole thing is temporary till we figure out a better solution. I have some ideas already. But for now we need at least something, that we are confided w/ production builds.
=> Introduce static builds in CI

.packit.yaml
...instead of just centos-stream-x86_64 which would collide with stream9
=> packit: stream target is now centos-stream-8

restraint.spec, third-party/Makefile, third-party/m4-1.4.18-glibc-sigstksz.patch
glibc made changes to SIGSTKSZ so the value can only be
determined at runtime instead of during preprocessing.
This translate static handling of the variable to dynamic
runtime.
Issue: 201
=> Fix: patch m4 to support glibc runtime SIGSTKSZ

rel-eng/releasers.conf
Since RHEL 5&6 no longer supported for future releases, removing
it from the list to be built.
Fixes: #213
=> Remove RHEL5&6 from builds

tests/valgrind.supp
Address recent valgrind errors that have suddenly appeared.
These issues are unrelated to restraint code since no code
has been changed since last successful valgrind run.
=> Fix: Resolve recent valgrind errors that popped up

.github/workflows/merge-checks.yml, .github/workflows/review-checks.yml
For the review-checks.yml file, it was previously updated to
Fedora:34 by pull 192 so only needed to drop fedora:32.
=> test: Add fedora:34/Drop 32 to GitHub workflows

restraint.spec
When Restraint rhel-8 image built, seeing the following error:
/usr/bin/ld: cannot find -lpcre2-8
Issue: 220
=> Fix: RHEL-8 build report pcre2-8 not found

init.d/Makefile, init.d/restraintd.service-legacy, restraint.spec
This change keeps restraintd from being oomkilled and since some testing
requires pushing the system into oomkill it's important to not kill the
test runner.
Fixes #224
Change-Id: Iec26c7b00761196a3a2491ba9f8802268283821c
=> Update systemd OOMPolicy for restraintd so it will continue to run

scripts/rstrnt-reboot
To reduce the likelihood of returning to the caller method, change
rstrnt-reboot to ignore SIGTERMs.  It will recognized SIGKILL
so there still is a small window of opportunity to return to caller.
Comments were also changed to make this clear.
Issue: 219
=> Fix: rstrnt-reboot to ignore SIGTERM

src/Makefile, third-party/Makefile
RHEL 7 & 8 have failed to build due to changes in pull request 197.
This changeset addresses the handling of third-party libraries
which are causing linkage issue in RHEL7 distro ppc architectures.
Static libraries must proceed dynamic library listings.  This
codeset orders static before dynamic as it was previously and
strips out some known dynamic libraries from 3rd-party static since
they are already defined in the dynamic library listing.
=> Fix: RHEL7 build breakage due to pull rqst 197

src/Makefile
When I run the latest image (post 0.3.3), I'm seeing the error
'libc.so.6(GLIBC_PRIVATE)(64bit) is needed by restraint.....'. 
The -llresolv must only be in dynamic library.  There was
a typo found in pull 228.  Once I did fixed typo, the rebuilt
image installed for both fedora34 and rhel7.
=> Fix: Fail to install - missing GLIBC_PRIVATE

restraint.spec, third-party/Makefile, third-party/glib_new_close_range_arg.patch
Changes in rawhide causing restraint images to fail to build.  The
cause was recent distros added an extra argument to the function
close_range().  This changeset applies a patch for fedora35 only.
=> Fix: f35/rawhide failing to build

restraint.spec
RHEL9 failing to build similar to Fedora35 build failures.  Need to
apply same third-party patches as done with Fedora35.
=> Fix: RHEL9 beta build failing

.github/workflows/review-checks.yml
I had to disable seccomp due to incompatibility between test runner and Fedora Glib version.
=> Enable Fedora 35 prerelease

.packit.yaml
=> Enable Fedora 35 in COPR builds

third-party/Makefile, third-party/bzip2-add-fPIE.patch
Trying to build latest rawhide rpms for restraint.  Discovered
Fedora-36 and 37 were not building. Build system showed errors
from libarchive builds with undefined references to methods
like BZ2_bzDecompressInit, BZ2_bzDecompress, etc.  Outside
of build system, I found errors requesting the bzip2 library
be recompiled with -fPIE which is what this changeset does.
Once changes applied, build errors went away and the
executable comes up and runs without issues.
=> libarchive requires bzip2 compiled with -fPIE

plugins/report_result.d/01_dmesg_check
In restraintd log files saw the following:
May 18 09:26:56 system1.example.com restraintd[2330]: ./01_dmesg_check: line 53: [: too many arguments
We are setting the `FALSESTRINGS` variable and the `|` symbols in the
value are interpreted by bash. Quote the value to prevent this.
=> Quote variable usage in 01_dmesg_check

.gitignore, docs/install.rst, restraint.spec, third-party/Makefile
Third party packages failing since zlib zlib-1.2.12 does not exist.
=> Fix: Upgrade ZLIB to zlib-1.2.13

releasenotes/notes/fix-fetch-f33da692d540ee7c.yaml, src/fetch_uri.c
When `fetch url` is used, restraint is copying anything that matches the pattern in `https://<snip>#pattern` regardless of the location in the received path.  If pattern is `include`, both `general/include, include` directories will match when it should only be `include`.  Restraint will now only select if it matches starting from beginning of received path NOT throughout directory path. But first, the first `string/` must be ignored from the received path since it is superfluous for the match since it includes the repo and branch name added by curl.
Jobs that include this repo-branch prefix in the fetch pattern will now fail with this changeset.
So fetching `https://<snip>#repo-branch/pattern` will fail.
Issue: 272
=> Fetch URI extract too many matched directories

docs/commands.rst, releasenotes/notes/fix-uefi-reboot-4552dec97663d4c9.yaml, scripts/rstrnt-prepare-reboot, scripts/rstrnt-reboot
When rstrnt-reboot is executed, it should set BootNext to current boot and NOT remove BootNext after a period of time like what is done in rstrnt-prepare-reboot.  rstrnt-reboot uses rstrnt-prepare-reboot so both have been modified to handle timer of zero which disables the reset of BootNext configuration.
=> Remove reset of UEFI NextBoot for rstrnt-reboot

src/fetch_git.c, src/fetch_git.h
Support to fetch branch 'master' as well if it fails to fetch branch 'main' as the default branch of some old/legacy repos is 'master'.
Fixes: #270
=> Fetch default branch 'main' instead of 'master'

docs/release-notes.rst
Tag 0.4.1 was skipped so release notes for 0.4.1 were actually released beneath 0.4.2.
=> Cleanup release notes for 0.4.2 and 0.4.1

src/fetch_git.c, src/fetch_git.h
The fix of https://github.com/restraint-harness/restraint/pull/279 was incomplete, which introduce a new failure that user has to specify the url like:
```xml
<fetch url="git://gerrit-git.engineering.redhat.com/kernel-tests?master#virt/beaker-core-task/install"/>
```
if the default branch of a repo is not 'main' but 'master'.  Hence, let's back out the related change.
=> Back out the default 'main' branch change

releasenotes/notes/revert-fetch-fix-395cd4f363ae20d7.yaml, src/fetch_uri.c
Backing out fix to provide precise directory matching for `repoRequires` and `fetch` operation. The problem is user's selection data is not precise.  User's have spoken and prefer to make their directory definition precise instead of triaging and fixing their selection data thus slowing down testing. Refer to close comments in issue 272 on 3/13 for details.
Issue: 272
=> Fix: Revert Fetch URL fix

src/process.c, src/xml.c, third-party/Makefile
At this moment the restraint builds with third-party libraries is broken due to a broken URL to pull zlib tarball. 
You can verify this patch by running the following commands in third-party directory.
```
$ make clean-tarballs
rm -rf libffi-3.3.tar.gz glib-2.68.0.tar.xz zlib-1.2.13.tar.gz bzip2-1.0.8.tar.gz libxml2-2.9.10.tar.gz curl-7.68.0.tar.bz2 libarchive-3.4.0.tar.gz xz-5.2.4.tar.gz sqlite-autoconf-3310100.tar.gz intltool-0.51.0.tar.gz libsoup-2.52.2.tar.xz autoconf-2.69.tar.gz json-c-0.13.1.tar.gz openssl-1.1.1k.tar.gz m4-1.4.19.tar.xz
$ make tarballs
...
```
=> Fixes for broken builds

docs/release-notes.rst, releasenotes/notes/dependency-upgrade-openssl-json-c-245cf07aeb019a3f.yaml, releasenotes/notes/extend-task-fetch-retries-b2295a6d7a82576f.yaml
The release notes contain all the major changes we made between 0.4.4 and 0.4.5. 
All other changes are related to the development environment or ensuring we can compile Restraint again.
This is the complete commit log
```
34cae42 Release Notes for Restraint version 0.4.5
cb70ae7 Add note for dependency updates
32902d2 Add note for extend task fetch
3f6a0e3 Update GH Actions to use Quay CR
811bce3 Use aliases to cover latest build roots
d5d7b8a Bump third-party json-c to 0.16
3e4eef4 Declare build_type_safety_c for Fedora 40
c299c44 Bump third-party OpenSSL to 1.1.1w
179b2df Suppress ReallocZero for libproxy/duktape
055a0a9 Add CentOS Stream static builds in review checks
af33aa7 Use pcre-static for CentOS static builds
e9fb8ae Add CentOS Stream container provision scripts
71ba7ab Use …
```
=> Release Notes 0.4.5

init.d/restraintd.service, legacy/Makefile, plugins/pkg_commands.d/centos, plugins/pkg_commands.d/fedora, restraint.conf, restraint.spec, src/utils.h
Ostree has bootable containers with a read-only filesystem.  This filesystem doesn't support dnf install nor current restraint directory layout and needs a few tweaks.  With these changes, restraint should work out of the box with bootable containers over ssh.  
Signed-off-by: Don Zickus <dzickus@redhat.com>
=> Changes to support ostree bootable containers

.github/workflows/review-checks.yml, rel-eng/releasers.conf, restraint.spec, third-party/Makefile, third-party/libsoup-gcc15-incompatible-pointers.patch
This patch fixes two build issues with CentOS-Stream 10.  The first is
using pcre2-static instead of pcre-static.  The second is to handle a
ppc failure that seems related to the build_type_safety_check_c put in
for Fedora > 40.  RHEL-10 is inheriting the same problem.
=> Add support for rhel-10 and centos-stream-10

restraint.spec, scripts/Makefile, specfiles/restraint-upstream.spec
With the previous commit b3bffb90d46a5, the need for /etc/restraint is not just limited to restraint-rhts it is also required by the main restraint package.  Let's reflect that change in the spec file.
Otherwise check-beaker fails to write to /etc/restraint/config.conf because the directory /etc/restraint doesn't exist.
=> Package /etc/restraint correctly

scripts/rstrnt-package
w/o this fix, the parameter --apply-live won't be applied when do rstrnt-package install.
=> scripts/rstrnt-package: fix rpm-ostree pkgs install

init.d/restraintd.service-legacy
Older releases like RHEL-8 and RHEL-7 use the restraintd.service-legacy file which did not get the 'StateDirectory=restraint' option added. This caused the /var/lib/restraint not to be created and various rstrnt scripts that wrote to that directory to not work.  Easy fix.
=> Fix systemd control of /var/lib/restraint to legacy service

docs/commands.rst, plugins/task_run.d/30_restore_events, scripts/rstrnt-sync-set, src/fetch_uri.c
The directory was changed from /var/lib/restraint already. So, the restraint-rhts-set script should follow the change.
Related: b3bffb90d46a5ec5a1699a5ce9100ea13fc7f003
Related: https://github.com/restraint-harness/restraint/issues/336
=> restraint-rhts-set should use /etc/restraint to record anything

.packit.yaml
Tito creates a tarball/rpm that says 'restraint-0.4.11', whereas PackIt uses <name>-<git tag> and creates 'restraint-restraint-0.4.11'.  This makes it hard to 'dnf update restraint' to use PackIt's rpm on top of the official Tito built rpm because restraint-0.4.11 > restraint-restraint-0.4.11.<packit extra>.prxxx.
Let's align the tarballs so we can use PackIt's rpm as a natural dnf update to the one in the provisioner allowing for CI tests.
=> Fix PackIt's tarball name to match tito's tarball name
