restraint-harness/restraint

- third-party/Makefile
- third-party/glib-nullstrings-gdbusauth.patch
Fixes: #6 
bug: [RHBZ#1802502](https://bugzilla.redhat.com/show_bug.cgi?id=1802502)
> Fix build issues on Fedora 32 / Fedora Rawhide (GCC10)

- containers/README.md
- containers/bootstrap.sh
- containers/provision/fedora:30.sh
- containers/provision/fedora:31.sh
- containers/provision/fedora:32.sh
- containers/provision/fedora:latest.sh
- containers/provision/fedora:rawhide.sh
- containers/run.sh
Add basic workflow to run review checks in containers.
Check containers/README.md for details.
Bug: 1801333
> tests: Run checks in containers

- .gitignore
- src/Makefile
Add test programs and environment file pattern to gitignore.
Remove environment files for tests in clean target.
> tests: Add cleanup for cmd tests

- src/test_utils.c
Add test to make sure that get_package_version handles the error when
the rpm program is not available.
Update existing tests where rpm is required to be skipped if the rpm
program is not available. This ensures that the suite can be run on
systems where rpm is not available.
> tests: Cover no rpm program in get_package_version

- docs/commands.rst
- docs/release-notes.rst
- docs/using.rst
- src/client.c
Providing more details in release notes and documentation to
better advise customer of the impact of this changeset.
Fix #12
> Revisit Release notes for sshlib removal

- src/server.c
The soup_server_listen_local() function tries to listen on both local
addresses, IPv4 and IPv6, and only succeeds when both are bind, even
when the loopback interface doesn't support one of the protocols.
Add rstrnt_listen_any_local() which succeeds when at least one local
address is bind.
Closes #42
> Setup server to listen on any local address

- .github/workflows/merge-checks.yml
- .github/workflows/review-checks.yml
- .packit.yaml
- rel-eng/releasers.conf
Fedora 30 is about end of life.
No further updates will be done.
> Drop support for Fedora 30

- src/client.c
Deprecate the host format in 0.1.45 keeping it backwards compatible.
- Accet the `[:host][/ssh_port]` arguments in the host option warning about deprecation
- Ignore `[:host][/ssh_port]` after parsing
- Fail parsing when host argument doesn't match format
Closes #68 
Relates to #12
> Deprecate [:host][/ssh_port] client host arguments

- docs/release-notes.rst
- docs/remove_rhts.rst
> Release notes for Restraint 0.2.1

- src/message.c
The json object for the body was never added to the json root for `logs`
messages, and it was not unreferenced.
> fix: json object leak in restraint_stdout_message

- docs/release-notes.rst
Release notes for new Z stream
> Release notes for 0.2.2

- docs/commands.rst
- docs/variables.rst
Change documentation with a few minor corrections:
* Resolve Warning error which have surfaced.
* Resolve incomplete doc reference.
Issue: 109
> FIX: Make a few minor doc clean-up changes

- docs/conf.py
- tox.ini
>  Use Read The Docs theme in local builds

- docs/release-notes.rst
> Release notes 0.2.3

- src/config.h
- src/dependency.h
- src/env.h
- src/fetch.h
- src/fetch_git.h
- src/fetch_uri.h
- src/process.h
- src/upload.h
> chore: Add missing include guards

- .packit.yaml
s390x arrived in COPR. Let's use it.
> Add s390x chroot for Packit CI

- docs/commands.rst
> FIX: resolve latest documentation warning

- releasenotes/notes/disable-log-manager-cee97935769367ac.yaml
- src/logging.h
- src/server.c
- src/task.c
Code for log manager remains but the feature is disabled until issues raised in #152 are resolved.
> Disable log manager

- src/Makefile
- src/logging.c
- src/logging.h
- src/task.c
- Dedupe log flushing
- Add helpers for log types
> Refactor log flushing and log type handling

- rel-eng/releasers.conf
Adding new rawhide (future 34). This changeset is pending creation
of f34 chroot.
Closes: 159
> Add eng-fedora-34/Drop eng-fedora-31 to release tags

- .gitignore
- src/config.h
- tests/Makefile
- tests/test_config.c
Covers,
- Setting the supported types
- Removing keys and groups
> test: Add cases for restraint_config_set

- .packit.yaml
- containers/provision/fedora:31.sh
> Fedora 31 EOL'd 

- .packit.yaml
Update build targets for Packit.
This should be **merged** no matter what is the result of CI. We need those CI targets to run for each PR to ensure we are fixing the stuff (and not breaking).
> Update build targets for Packit

- rel-eng/releasers.conf
Update the release selector file to drop Fedora32 and add
Fedora35.
> Drop Fedora32/add Fedora35 to release file

- rel-eng/releasers.conf
a Please enter the commit message for your changes. Lines starting
> Drop Fedora34/Add Fedora37&RHEL-9 to release file

- .github/workflows/review-checks.yml
- containers/provision/centos:stream8.sh
- containers/provision/centos:stream9.sh
- restraint.spec
- Added provision scripts for centos:stream8 and centos:stream9 containers
- Fixed static builds for CentOS Stream
- Added CentOS Stream static build in review checks
> Add support for CentOS Stream containers

- .github/workflows/merge-checks.yml
- .github/workflows/review-checks.yml
- third-party/Makefile
- third-party/m4-1.4.19-fortify-source.patch
- third-party/m4-1.4.19-nodiscard-gcc15.patch
v1 and v2 of upload-artifact is deprectated, use newer versions.
I don't know what the impact is and am just blindly updating them to see what falls out.
> Update github actions to checkout@v3 and upload-artifact@v4

- src/cmd_abort.c
- src/cmd_log.c
- src/cmd_result.c
- src/cmd_watchdog.c
- src/upload.c
- src/upload.h
- tests/Makefile
- tests/test_upload.c
This slipped into my release branch.  Poor workflow skills.
This reverts commit 7b8276af3945497804d77f7d1ec6a6bb57d3f25a.
> Revert "Convert src/cmd_ files from libsoup to libcurl"

- scripts/rstrnt-package
- tests/test-dummies/fakerpm
- tests/test-dummies/fakeyum
- tests/test_dependency.c
On newer systems rpm has dropped the older digest modes.
Change-Id: Iedd1a75c354e58d115865337aa55666ff5fc526d
> Update to handle older packages
